---

# Provision the cluster
- name: K3s Deployment
  become: yes
  gather_facts: True
  hosts: kube_cluster
  max_fail_percentage: 0
  roles:
    # - hardening
    # I gave up fixing hardening to work with Ubuntu 20.04
    # Using this instead: https://github.com/alivx/CIS-Ubuntu-20.04-Ansible
    # Checkpoint Remarks
    # - cis-ubuntu-2004-ansible
    - k3s-dependencies
    # - k3s-deploy

...
